[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "file:./dev.db"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200